
export const select = {
    SubArea: [
        { label: "WORT KETTLE" },
        { label: "TORRE DE MOLIENDA" },
        { label: "CONOCIMIENTOS" },
        { label: "BAGAZO/SYE" },
        { label: "BLOQUE FRIO" },
        { label: "GENERAL" },
        { label: "NO DATA AVAILABLE" }
    ],
    Areas: [
        { label: "GENERAL SERVICES" },
        { label: "SILOS" },
        { label: "MILLING" },
        { label: "BREWHOUSE" },
        { label: "BREWING" },
        { label: "FERMENTATION" },
        { label: "MATURATION" },
        { label: "CENTRIFUGE" },
        { label: "FILTRATION" },
        { label: "DILUTION WATER" },
        { label: "BRIGHT BEER TANKS" },
        { label: "PACKAGING" },
        { label: "CHEMICAL ISLAND & CIP" },
        { label: "SYRUP HOUSE" },
        { label: "LOGISTIC TIER 1" },
        { label: "LOGISTIC TIER 2" },
        { label: "CO2 RECOVERY" },
        { label: "REFRIGERATION" },
        { label: "WELLS" },
        { label: "WATER TREATMENT PLANT" },
        { label: "COMPRESSED AIR" },
        { label: "ELECTRICAL SUBSTATION (HV)" },
        { label: "ELECTRICAL SUBSTATION (MV)" },
        { label: "ELECTRICAL SUBSTATION (LV)" },
        { label: "STEAM GENERATION" },
        { label: "BIOLOGICAL TREATMENT SYSTEM" },
        { label: "TERTIARY SYSTEM" },
        { label: "SANITARY PLANT" },
        { label: "AUTOMATION & INDUSTRIAL NETWORK" },
        { label: "MAINTENANCE" },
        { label: "IT" },
        { label: "LABORATORY" },
        { label: "WORKSHOP" },
        { label: "OFFICES" },
        { label: "SUBPRODUCTS" }
    ],
    BU: [
        { label: "CAC" },
        { label: "COL" },
        { label: "PEC" },
        { label: "MEX" }
    ],
    Pais: [
        { label: "BARBADOS" },
        { label: "COLOMBIA" },
        { label: "CUBA" },
        { label: "DOMINICANA" },
        { label: "ECUADOR" },
        { label: "EL SALVADOR" },
        { label: "GUATEMALA" },
        { label: "HONDURAS" },
        { label: "MÉXICO" },
        { label: "PANAMA" },
        { label: "PERÚ" },
        { label: "SAINT VINCENT" }
    ],
    TipoLinea: [
        { label: "BREWLINE", Id_LineTypes: '1' },
        { label: "BOTTLE", Id_LineTypes: '2' },
        { label: "CAN", Id_LineTypes: '3' },
        { label: "PET", Id_LineTypes: '4' },
        { label: "KEG", Id_LineTypes: '5' },
        { label: "SPECIAL KEG", Id_LineTypes: '6' },
        { label: "OTHER", Id_LineTypes: '7' }
    ],
    Planta: [
        { label: "APAN" },
        { label: "BARBADOS" },
        { label: "BARRANQUILLA" },
        { label: "BOYACA" },
        { label: "BUCARAMANGA" },
        { label: "FABRICA DE TAPAS DE TOCANCIPA" },
        { label: "ETIQUETAS IMPRESUR & INDUGRAL" },
        { label: "MEDELLIN" },
        { label: "MALTERIA TIBITO" },
        { label: "TONCACIPA" },
        { label: "MALTERIA TROPICAL" },
        { label: "VALLE" },
        { label: "HOLGUIN" },
        { label: "DOMINICANA" },
        { label: "HATO NUEVO" },
        { label: "GUAYAQUIL" },
        { label: "QUITO" },
        { label: "MALTERIA DE GUAYAQUIL" },
        { label: "LA CONSTANCIA BEER" },
        { label: "EL SALVADOR CSD" },
        { label: "LA CONSTANCIA WALTER" },
        { label: "ZACAPA" },
        { label: "SAN PEDRO SULA BEER" },
        { label: "SAN PEDRO SULA CSD" },
        { label: "CEBADAS Y MALTAS" },
        { label: "GUADALAJARA" },
        { label: "MALTERIA ZACATECAS" },
        { label: "MAZATLÁN" },
        { label: "MODELO MÉXICO" },
        { label: "SALAMANCA (CASAL)" },
        { label: "TORREÓN" },
        { label: "TUXTEPEC" },
        { label: "YUCATAN" },
        { label: "ZACATECAS" },
        { label: "CUCAPÁ (CRAFT)" },
        { label: "PASADENA" },
        { label: "AREQUIPA" },
        { label: "ATE" },
        { label: "CUSCO" },
        { label: "HUACHIPA" },
        { label: "MALTERIA DE LIMA" },
        { label: "MOTUPE" },
        { label: "SAN JUAN (PUCALLPA)" },
        { label: "SAN MATEO (HUAROCHIRI)" },
        { label: "BARBARIAN (CRAFT)" },
        { label: "SAINT VINCENT" },
        { label: "BOGOTÁ BREWERY COMPANY (CRAFT)" }
    ],
}